class_name ActivityEvent

enum Type {
	TURN_CHANGE,
	DICE_ROLLED,
	RESOURCES_DISTRIBUTED,
	PIECE_PLACED,
	DEVELOPMENT_CARD_BOUGHT,
	DEVELOPMENT_CARD_PLAYED,
	BANK_TRADE,
	RESOURCE_STOLEN,
	TITLE_CHANGED,
	VP_CHANGED,
	TITLE_LOST,
}
